// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2PlaFH8lu1EtkrZ-vDDC73l3TFFKJU-s',
    appId: '1:209496617956:web:0e26548b725f9f0ba80df1',
    messagingSenderId: '209496617956',
    projectId: 'parley-motmot',
    authDomain: 'parley-motmot.firebaseapp.com',
    storageBucket: 'parley-motmot.appspot.com',
    measurementId: 'G-NNE347G6F6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7hmgVr1cT26O-rJZjpoW849PBaujv9JA',
    appId: '1:209496617956:android:405f9b27f983eadea80df1',
    messagingSenderId: '209496617956',
    projectId: 'parley-motmot',
    storageBucket: 'parley-motmot.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7XbMvgdoRggTrifpHlUaqPqwfQ2DE-oc',
    appId: '1:209496617956:ios:91fb34f4b322637fa80df1',
    messagingSenderId: '209496617956',
    projectId: 'parley-motmot',
    storageBucket: 'parley-motmot.appspot.com',
    iosBundleId: 'com.parley.app',
  );

}